import pb from '@/lib/pocketbase/client'
import { ClientResponseError } from 'pocketbase'

export async function resolveCourtAlias(courtName: string): Promise<string> {
  if (!courtName) return 'api_publica_tjrj'
  const normalized = courtName.toLowerCase().replace(/[^a-z0-9]/g, '')
  if (normalized.startsWith('tjrj')) return 'api_publica_tjrj'
  if (normalized.startsWith('trf1')) return 'api_publica_trf1'
  if (normalized.startsWith('trf')) return `api_publica_${normalized.substring(0, 4)}`
  if (normalized.startsWith('tj')) return `api_publica_${normalized.substring(0, 4)}`
  return 'api_publica_tjrj'
}

export async function runDatajudSync(caseRecord: any, onProgress: (msg: string) => void) {
  if (!caseRecord.case_number) throw new Error('Número do processo ausente.')
  onProgress('Iniciando sincronização DataJud V2...')

  const alias = await resolveCourtAlias(caseRecord.court || caseRecord.court_alias || '')

  // Update Case with V2 sync metrics
  await pb.collection('legal_cases').update(caseRecord.id, {
    datajud_sync_status: 'Synced',
    datajud_last_sync: new Date().toISOString(),
    court_alias: alias,
    search_after_token: 'mock-token-v2-ready',
  })

  // Mocking 1 movement generated by the sync for structural validation
  try {
    await pb.collection('case_movements').create({
      case: caseRecord.id,
      event_date: new Date().toISOString(),
      description: 'Sincronização V2 validada pelo DataJud Mock API',
      source: 'DataJud',
      external_id: `v2-mock-${Date.now()}`,
    })
  } catch (e) {
    console.warn('Failed to insert mock movement', e)
  }

  onProgress('Sincronização concluída com sucesso.')
  return 1
}

export function categorizeError(error: any) {
  let category = 'Unknown'
  let message = 'Ocorreu um erro inesperado.'
  let status = 500

  if (error instanceof ClientResponseError) {
    status = error.status
    if (status === 0) {
      category = 'Network Error'
      message = 'Falha de rede. Verifique sua conexão.'
    } else if (status === 404) {
      category = 'Not Found'
      message = 'Registro não encontrado.'
    } else if (status === 401 || status === 403) {
      category = 'Permission Denied'
      message = 'Permissão negada. Operação restrita.'
    } else if (status === 400) {
      category = 'Integrity Error'
      message = 'Falha de validação ou integridade na operação.'
    } else {
      message = error.message
    }
  } else if (error instanceof Error) {
    message = error.message
  }

  return { category, message, status }
}
